services:
  samba:
    image: lscr.io/linuxserver/samba:latest
    container_name: samba
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    volumes:
      - ${ROOT_CONFIG_DIR}/samba:/config
      - ${ROOT_DATA_DIR}:/data
    ports:
      - "445:445"
    networks:
      - homelab_net

networks:
  homelab_net:
    external: true
