services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    #network_mode: host
    environment:
      TZ: ${TZ}
    volumes:
      - ${ROOT_CONFIG_DIR}/jellyfin:/config
      - ${ROOT_DATA_DIR}/media:/data/media
    networks:
      - homelab_net

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      LOG_LEVEL: debug
    volumes:
      - ${ROOT_CONFIG_DIR}/jellyseerr:/app/config
    networks:
      - homelab_net

  komga:
    image: gotson/komga:latest
    container_name: komga
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      # Optional: set JVM memory limits if your homelab system is tight on RAM (e.g., -Xmx1g)
      # - JAVA_TOOL_OPTIONS=-Xmx1g 
    volumes:
      - ${ROOT_CONFIG_DIR}/komga:/config
      # Maps your main media directory so Komga can see your comic folder
      - ${ROOT_DATA_DIR}/media/Books:/Books
    ports:
      - 25600:25600
    networks:
      - homelab_net

networks:
  homelab_net:
    external: true
